### ISSUE TITLE
Subdirectory in OUTPUT is not created

### ISSUE THREAD

**Issue by gylead** [c3d/make-it-quick#1]
Hello,

I defined OUTPUT=build/bin/ in my Makefile. This doesn't work because the directory is not created. As a quick fix I added a line

.config: $(OUTPUT).mkdir-only

right after

.config: .hello

Regards, Jochen

**Comment by gylead** [comment]
I don't care for that (even didn't know until your reply) but I updated my profile (Jochen Becher <jochen_becher@gmx.de>) if you want to mention me.

**Comment by c3d** [comment]
Should be fixed in master now. I took a slightly different approach, so put "reported-by" instead of Signed-of-by ;-)
